# Generated by Django 2.1 on 2019-04-01 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0003_auto_20190327_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_hora', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario')),
            ],
        ),
    ]
