# Generated by Django 2.2 on 2019-04-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horaextra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='marcada',
            field=models.BooleanField(default=False),
        ),
    ]
