# Generated by Django 2.1 on 2019-03-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentos_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='arquivo',
            field=models.FileField(default=1, upload_to='documentos'),
            preserve_default=False,
        ),
    ]
