# Generated by Django 2.1 on 2019-03-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentos_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='arquivo',
        ),
    ]
